//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.AMIntegrationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AMIntegrationSoap12", Namespace="http://bankmuscat.com/AMIntegrationService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AMIntegrationRes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AMIntegrationReq))]
    public partial class AMIntegration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListofAMCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListofAMRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListSuiteContactOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AMIntegration() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_AMIntegrationService_AMIntegration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListofAMCustomerCompletedEventHandler GetListofAMCustomerCompleted;
        
        /// <remarks/>
        public event GetListofAMRegistrationCompletedEventHandler GetListofAMRegistrationCompleted;
        
        /// <remarks/>
        public event GetListSuiteContactCompletedEventHandler GetListSuiteContactCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bankmuscat.com/AMIntegrationService/GetListofAMCustomer", RequestNamespace="http://bankmuscat.com/AMIntegrationService", ResponseNamespace="http://bankmuscat.com/AMIntegrationService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetListofAMCustomerResponse GetListofAMCustomer(GetListofAMCustomerRequest GetListofAMCustomerReq, System.DateTime StartDate, System.DateTime EndDate) {
            object[] results = this.Invoke("GetListofAMCustomer", new object[] {
                        GetListofAMCustomerReq,
                        StartDate,
                        EndDate});
            return ((GetListofAMCustomerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListofAMCustomerAsync(GetListofAMCustomerRequest GetListofAMCustomerReq, System.DateTime StartDate, System.DateTime EndDate) {
            this.GetListofAMCustomerAsync(GetListofAMCustomerReq, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetListofAMCustomerAsync(GetListofAMCustomerRequest GetListofAMCustomerReq, System.DateTime StartDate, System.DateTime EndDate, object userState) {
            if ((this.GetListofAMCustomerOperationCompleted == null)) {
                this.GetListofAMCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListofAMCustomerOperationCompleted);
            }
            this.InvokeAsync("GetListofAMCustomer", new object[] {
                        GetListofAMCustomerReq,
                        StartDate,
                        EndDate}, this.GetListofAMCustomerOperationCompleted, userState);
        }
        
        private void OnGetListofAMCustomerOperationCompleted(object arg) {
            if ((this.GetListofAMCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListofAMCustomerCompleted(this, new GetListofAMCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bankmuscat.com/AMIntegrationService/GetListofAMRegistration", RequestNamespace="http://bankmuscat.com/AMIntegrationService", ResponseNamespace="http://bankmuscat.com/AMIntegrationService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetListofAMRegistrationResponse GetListofAMRegistration(GetListofAMRegistrationRequest GetListofAMAuctionReq) {
            object[] results = this.Invoke("GetListofAMRegistration", new object[] {
                        GetListofAMAuctionReq});
            return ((GetListofAMRegistrationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListofAMRegistrationAsync(GetListofAMRegistrationRequest GetListofAMAuctionReq) {
            this.GetListofAMRegistrationAsync(GetListofAMAuctionReq, null);
        }
        
        /// <remarks/>
        public void GetListofAMRegistrationAsync(GetListofAMRegistrationRequest GetListofAMAuctionReq, object userState) {
            if ((this.GetListofAMRegistrationOperationCompleted == null)) {
                this.GetListofAMRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListofAMRegistrationOperationCompleted);
            }
            this.InvokeAsync("GetListofAMRegistration", new object[] {
                        GetListofAMAuctionReq}, this.GetListofAMRegistrationOperationCompleted, userState);
        }
        
        private void OnGetListofAMRegistrationOperationCompleted(object arg) {
            if ((this.GetListofAMRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListofAMRegistrationCompleted(this, new GetListofAMRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bankmuscat.com/AMIntegrationService/GetListSuiteContact", RequestNamespace="http://bankmuscat.com/AMIntegrationService", ResponseNamespace="http://bankmuscat.com/AMIntegrationService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetListofSuiteContactResponse GetListSuiteContact(GetListofSuiteContactRequest GetSuiteContactRequest) {
            object[] results = this.Invoke("GetListSuiteContact", new object[] {
                        GetSuiteContactRequest});
            return ((GetListofSuiteContactResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListSuiteContactAsync(GetListofSuiteContactRequest GetSuiteContactRequest) {
            this.GetListSuiteContactAsync(GetSuiteContactRequest, null);
        }
        
        /// <remarks/>
        public void GetListSuiteContactAsync(GetListofSuiteContactRequest GetSuiteContactRequest, object userState) {
            if ((this.GetListSuiteContactOperationCompleted == null)) {
                this.GetListSuiteContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListSuiteContactOperationCompleted);
            }
            this.InvokeAsync("GetListSuiteContact", new object[] {
                        GetSuiteContactRequest}, this.GetListSuiteContactOperationCompleted, userState);
        }
        
        private void OnGetListSuiteContactOperationCompleted(object arg) {
            if ((this.GetListSuiteContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListSuiteContactCompleted(this, new GetListSuiteContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofAMCustomerRequest : AMIntegrationReq {
        
        private string referenceIDField;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofSuiteContactRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofAMRegistrationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofAMCustomerRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class AMIntegrationReq {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AMRegistration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AMAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AMCustomer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class EntityBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class AMRegistration : EntityBase {
        
        private string customer_idField;
        
        private string paddleField;
        
        private string created_atField;
        
        private AMCustomer customerField;
        
        /// <remarks/>
        public string Customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public string Paddle {
            get {
                return this.paddleField;
            }
            set {
                this.paddleField = value;
            }
        }
        
        /// <remarks/>
        public string Created_at {
            get {
                return this.created_atField;
            }
            set {
                this.created_atField = value;
            }
        }
        
        /// <remarks/>
        public AMCustomer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class AMCustomer : EntityBase {
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private string deviceLocationField;
        
        private string statusField;
        
        private string assignToGroupField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string netsuiteIdField;
        
        private string debitCardGroupField;
        
        private string faxField;
        
        private string commentsField;
        
        private string auctionRecordIdField;
        
        private string passwordField;
        
        private string email_addressField;
        
        private string companynameField;
        
        private AMAddress[] addressesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceLocation {
            get {
                return this.deviceLocationField;
            }
            set {
                this.deviceLocationField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string AssignToGroup {
            get {
                return this.assignToGroupField;
            }
            set {
                this.assignToGroupField = value;
            }
        }
        
        /// <remarks/>
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string NetsuiteId {
            get {
                return this.netsuiteIdField;
            }
            set {
                this.netsuiteIdField = value;
            }
        }
        
        /// <remarks/>
        public string DebitCardGroup {
            get {
                return this.debitCardGroupField;
            }
            set {
                this.debitCardGroupField = value;
            }
        }
        
        /// <remarks/>
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string AuctionRecordId {
            get {
                return this.auctionRecordIdField;
            }
            set {
                this.auctionRecordIdField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string email_address {
            get {
                return this.email_addressField;
            }
            set {
                this.email_addressField = value;
            }
        }
        
        /// <remarks/>
        public string companyname {
            get {
                return this.companynameField;
            }
            set {
                this.companynameField = value;
            }
        }
        
        /// <remarks/>
        public AMAddress[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class AMAddress : EntityBase {
        
        private string street_addressField;
        
        private string country_codeField;
        
        private string localityField;
        
        private string regionField;
        
        private string postal_codeField;
        
        private string typeField;
        
        /// <remarks/>
        public string Street_address {
            get {
                return this.street_addressField;
            }
            set {
                this.street_addressField = value;
            }
        }
        
        /// <remarks/>
        public string Country_code {
            get {
                return this.country_codeField;
            }
            set {
                this.country_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofSuiteContactResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofAMRegistrationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetListofAMCustomerResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class AMIntegrationRes {
        
        private int statusCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofSuiteContactResponse : AMIntegrationRes {
        
        private string referenceIDField;
        
        private AMCustomer[] listField;
        
        /// <remarks/>
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        public AMCustomer[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofAMRegistrationResponse : AMIntegrationRes {
        
        private string referenceIDField;
        
        private AMRegistration[] listField;
        
        /// <remarks/>
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        public AMRegistration[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofAMCustomerResponse : AMIntegrationRes {
        
        private string referenceIDField;
        
        private AMCustomer[] listField;
        
        /// <remarks/>
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        public AMCustomer[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofSuiteContactRequest : AMIntegrationReq {
        
        private string referenceIDField;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankmuscat.com/AMIntegrationService")]
    public partial class GetListofAMRegistrationRequest : AMIntegrationReq {
        
        private string referenceIDField;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetListofAMCustomerCompletedEventHandler(object sender, GetListofAMCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListofAMCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListofAMCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetListofAMCustomerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetListofAMCustomerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetListofAMRegistrationCompletedEventHandler(object sender, GetListofAMRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListofAMRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListofAMRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetListofAMRegistrationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetListofAMRegistrationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetListSuiteContactCompletedEventHandler(object sender, GetListSuiteContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListSuiteContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListSuiteContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetListofSuiteContactResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetListofSuiteContactResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591