//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string year_of_birth_c { get; set; }
        public string year_of_death_c { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public Nullable<int> modifiedby_id { get; set; }
    }
}
