//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSIntegration.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PundolesEntities : DbContext
    {
        public PundolesEntities()
            : base("name=PundolesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dropdown_master> dropdown_master { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<artist> artists { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
    
        public virtual ObjectResult<GetDropDownMasterData_Result> GetDropDownMasterData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDropDownMasterData_Result>("GetDropDownMasterData");
        }
    
        public virtual ObjectResult<ViewContactData_Result> ViewContactData(Nullable<int> contact_id)
        {
            var contact_idParameter = contact_id.HasValue ?
                new ObjectParameter("contact_id", contact_id) :
                new ObjectParameter("contact_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewContactData_Result>("ViewContactData", contact_idParameter);
        }
    
        public virtual ObjectResult<GetContactsData_Result> GetContactsData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetContactsData_Result>("GetContactsData");
        }
    
        public virtual ObjectResult<GetUsersData_Result> GetUsersData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersData_Result>("GetUsersData");
        }
    
        public virtual ObjectResult<ViewUserData_Result> ViewUserData(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewUserData_Result>("ViewUserData", user_idParameter);
        }
    
        public virtual ObjectResult<GetArtistsData_Result> GetArtistsData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetArtistsData_Result>("GetArtistsData");
        }
    }
}
