//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_hash { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone_home { get; set; }
        public string phone_mobile { get; set; }
        public string department { get; set; }
        public string primary_email { get; set; }
        public string alternate_email { get; set; }
        public Nullable<int> report_to_id { get; set; }
        public string user_type { get; set; }
        public string user_status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public Nullable<int> modifiedby_id { get; set; }
    }
}
